//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTurno
    {
        public int IdDetalleTurno { get; set; }
        public int IdTurno { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdPersonalEmergencia { get; set; }
        public int IdEstado { get; set; }
        public string Comentario { get; set; }
    
        public virtual PersonalEmergencia PersonalEmergencia { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
