//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public Estados()
        {
            this.Requerimiento_Insumo = new HashSet<Requerimiento_Insumo>();
        }
    
        public int IdEstado { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Requerimiento_Insumo> Requerimiento_Insumo { get; set; }
    }
}
