//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumo
    {
        public Insumo()
        {
            this.Requerimiento_Insumo = new HashSet<Requerimiento_Insumo>();
        }
    
        public int IdInsumo { get; set; }
        public string NombreInsumo { get; set; }
        public string Marca { get; set; }
        public string Linea { get; set; }
    
        public virtual ICollection<Requerimiento_Insumo> Requerimiento_Insumo { get; set; }
    }
}
