//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionRicardoPalma : DbContext
    {
        public ConnectionRicardoPalma()
            : base("name=ConnectionRicardoPalma")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Destino> Destino { get; set; }
        public virtual DbSet<DetalleTurno> DetalleTurno { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Insumo> Insumo { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<PersonalEmergencia> PersonalEmergencia { get; set; }
        public virtual DbSet<Prioridad> Prioridad { get; set; }
        public virtual DbSet<Protocolo> Protocolo { get; set; }
        public virtual DbSet<Requerimiento_Insumo> Requerimiento_Insumo { get; set; }
        public virtual DbSet<RequerimientoInsumo> RequerimientoInsumo { get; set; }
        public virtual DbSet<Sintoma> Sintoma { get; set; }
        public virtual DbSet<TicketEmergencia> TicketEmergencia { get; set; }
        public virtual DbSet<TicketSalaObservacion> TicketSalaObservacion { get; set; }
        public virtual DbSet<TicketTraumaShockTopico> TicketTraumaShockTopico { get; set; }
        public virtual DbSet<TipoPaciente> TipoPaciente { get; set; }
        public virtual DbSet<Tratamiento> Tratamiento { get; set; }
        public virtual DbSet<Triaje> Triaje { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
