//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.TicketEmergencia = new HashSet<TicketEmergencia>();
        }
    
        public int IdPaciente { get; set; }
        public int IdTipoPaciente { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int dni { get; set; }
    
        public virtual TipoPaciente TipoPaciente { get; set; }
        public virtual ICollection<TicketEmergencia> TicketEmergencia { get; set; }
    }
}
