//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequerimientoTurno
    {
        public int IdRequerimientoTurno { get; set; }
        public int IdPersonalEmergencia { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
        public string Motivo { get; set; }
        public bool EsAprobado { get; set; }
    
        public virtual PersonalEmergencia PersonalEmergencia { get; set; }
    }
}
