//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequerimientoInsumo
    {
        public RequerimientoInsumo()
        {
            this.Requerimiento_Insumo = new HashSet<Requerimiento_Insumo>();
        }
    
        public int IdRequerimientoInsumo { get; set; }
        public int IdPersonalEmergencia { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
    
        public virtual PersonalEmergencia PersonalEmergencia { get; set; }
        public virtual ICollection<Requerimiento_Insumo> Requerimiento_Insumo { get; set; }
    }
}
