//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimiento_Insumo
    {
        public int IdRequerimiento_Insumo { get; set; }
        public int IdRequerimientoInsumo { get; set; }
        public int IdInsumo { get; set; }
        public int IdSala { get; set; }
        public string Sala { get; set; }
        public int Cantidad { get; set; }
        public string Motivo { get; set; }
        public int IdEstado { get; set; }
        public bool EsAutorizado { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Insumo Insumo { get; set; }
        public virtual RequerimientoInsumo RequerimientoInsumo { get; set; }
    }
}
