//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTraumaShockTopico
    {
        public TicketTraumaShockTopico()
        {
            this.TicketEmergencia = new HashSet<TicketEmergencia>();
        }
    
        public int IdTicketTrauma { get; set; }
        public Nullable<System.DateTime> Ingreso { get; set; }
        public Nullable<System.DateTime> Egreso { get; set; }
        public string Diagnostico { get; set; }
        public Nullable<bool> EsTraumaShock { get; set; }
    
        public virtual ICollection<TicketEmergencia> TicketEmergencia { get; set; }
    }
}
