//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketEmergencia
    {
        public TicketEmergencia()
        {
            this.Triaje = new HashSet<Triaje>();
        }
    
        public int IdTicketEmergencia { get; set; }
        public int IdPaciente { get; set; }
        public Nullable<int> IdDestino { get; set; }
        public Nullable<bool> EsViolencia { get; set; }
        public Nullable<int> IdTicketTrauma { get; set; }
        public Nullable<int> IdTicketSala { get; set; }
        public Nullable<int> IdTratamiento { get; set; }
        public Nullable<int> IdPersonalEmergencia { get; set; }
        public Nullable<System.DateTime> Ingreso { get; set; }
        public Nullable<System.DateTime> Egreso { get; set; }
    
        public virtual Destino Destino { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual PersonalEmergencia PersonalEmergencia { get; set; }
        public virtual TicketSalaObservacion TicketSalaObservacion { get; set; }
        public virtual TicketTraumaShockTopico TicketTraumaShockTopico { get; set; }
        public virtual Tratamiento Tratamiento { get; set; }
        public virtual ICollection<Triaje> Triaje { get; set; }
    }
}
