//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPaciente
    {
        public TipoPaciente()
        {
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int IdTipoPaciente { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
