//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicardoPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Triaje
    {
        public int IdTriaje { get; set; }
        public int IdPrioridad { get; set; }
        public int IdTicketEmergencia { get; set; }
        public int IdSintoma { get; set; }
    
        public virtual Prioridad Prioridad { get; set; }
        public virtual Sintoma Sintoma { get; set; }
        public virtual TicketEmergencia TicketEmergencia { get; set; }
    }
}
